version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    restart: on-failure:3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:2.8.23
    restart: on-failure:3
    ports:
      - "6379:6379"

  app:
    build: .
    restart: on-failure:3
    command: bash run_app.sh
    expose:
      - 8000
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    restart: on-failure:3
    command: bash run_celery.sh
    depends_on:
      - postgres
      - redis
      - app

  nginx:
    build: ./nginx
    restart: on-failure:3
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_volume: