# Generated by Django 2.2.7 on 2020-04-08 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200408_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='ab_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
