# Generated by Django 2.2.7 on 2020-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200408_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
